export interface CountryCode {
  name: string;
  dialCode: string;
  iso2: string;
  /** [min, max] digits expected in the national number, after the dial code. Falls back to a generic range when omitted — see getPhoneLengthRange. */
  phoneLength?: [number, number];
}

// Default selection for the signup phone field — this store's home market.
export const DEFAULT_COUNTRY_ISO2 = 'UG';

// Fallback for countries below without a hand-verified phoneLength: E.164
// caps the whole number (dial code + national number) at 15 digits, and
// almost every national number in use today is at least 7 digits.
const FALLBACK_PHONE_LENGTH: [number, number] = [7, 12];

/** Finds the phoneLength range for a dial code (falls back if not matched or unspecified). */
export function getPhoneLengthRange(dialCode: string): [number, number] {
  return COUNTRY_CODES.find((c) => c.dialCode === dialCode)?.phoneLength ?? FALLBACK_PHONE_LENGTH;
}

// Standard ITU E.164 country calling codes, sorted alphabetically by country
// name. A few countries share a dial code (e.g. the North American +1 zone,
// French/Dutch Caribbean territories) — that's expected, not a duplicate bug.
// phoneLength = [min, max] digits in the national number (after the dial
// code, excluding any domestic trunk "0"). Precisely known for this store's
// core East African market and other major markets; a sane generic range
// elsewhere rather than a guessed exact figure, to avoid rejecting valid
// numbers on unverified data.
export const COUNTRY_CODES: CountryCode[] = [
  { name: 'Afghanistan', dialCode: '+93', iso2: 'AF', phoneLength: [9, 9] },
  { name: 'Albania', dialCode: '+355', iso2: 'AL' },
  { name: 'Algeria', dialCode: '+213', iso2: 'DZ', phoneLength: [9, 9] },
  { name: 'Andorra', dialCode: '+376', iso2: 'AD' },
  { name: 'Angola', dialCode: '+244', iso2: 'AO' },
  { name: 'Argentina', dialCode: '+54', iso2: 'AR', phoneLength: [10, 10] },
  { name: 'Armenia', dialCode: '+374', iso2: 'AM', phoneLength: [8, 8] },
  { name: 'Australia', dialCode: '+61', iso2: 'AU', phoneLength: [9, 9] },
  { name: 'Austria', dialCode: '+43', iso2: 'AT', phoneLength: [10, 11] },
  { name: 'Azerbaijan', dialCode: '+994', iso2: 'AZ', phoneLength: [9, 9] },
  { name: 'Bahamas', dialCode: '+1242', iso2: 'BS' },
  { name: 'Bahrain', dialCode: '+973', iso2: 'BH', phoneLength: [8, 8] },
  { name: 'Bangladesh', dialCode: '+880', iso2: 'BD', phoneLength: [10, 10] },
  { name: 'Barbados', dialCode: '+1246', iso2: 'BB' },
  { name: 'Belarus', dialCode: '+375', iso2: 'BY', phoneLength: [9, 9] },
  { name: 'Belgium', dialCode: '+32', iso2: 'BE', phoneLength: [9, 9] },
  { name: 'Belize', dialCode: '+501', iso2: 'BZ' },
  { name: 'Benin', dialCode: '+229', iso2: 'BJ' },
  { name: 'Bhutan', dialCode: '+975', iso2: 'BT' },
  { name: 'Bolivia', dialCode: '+591', iso2: 'BO', phoneLength: [8, 8] },
  { name: 'Bosnia and Herzegovina', dialCode: '+387', iso2: 'BA' },
  { name: 'Botswana', dialCode: '+267', iso2: 'BW' },
  { name: 'Brazil', dialCode: '+55', iso2: 'BR', phoneLength: [10, 11] },
  { name: 'Brunei', dialCode: '+673', iso2: 'BN' },
  { name: 'Bulgaria', dialCode: '+359', iso2: 'BG' },
  { name: 'Burkina Faso', dialCode: '+226', iso2: 'BF' },
  { name: 'Burundi', dialCode: '+257', iso2: 'BI', phoneLength: [8, 8] },
  { name: 'Cambodia', dialCode: '+855', iso2: 'KH', phoneLength: [8, 9] },
  { name: 'Cameroon', dialCode: '+237', iso2: 'CM' },
  { name: 'Canada', dialCode: '+1', iso2: 'CA', phoneLength: [10, 10] },
  { name: 'Cape Verde', dialCode: '+238', iso2: 'CV' },
  { name: 'Central African Republic', dialCode: '+236', iso2: 'CF' },
  { name: 'Chad', dialCode: '+235', iso2: 'TD' },
  { name: 'Chile', dialCode: '+56', iso2: 'CL', phoneLength: [9, 9] },
  { name: 'China', dialCode: '+86', iso2: 'CN', phoneLength: [11, 11] },
  { name: 'Colombia', dialCode: '+57', iso2: 'CO', phoneLength: [10, 10] },
  { name: 'Comoros', dialCode: '+269', iso2: 'KM' },
  { name: 'Congo (DRC)', dialCode: '+243', iso2: 'CD' },
  { name: 'Congo (Republic)', dialCode: '+242', iso2: 'CG' },
  { name: 'Costa Rica', dialCode: '+506', iso2: 'CR' },
  { name: "Côte d'Ivoire", dialCode: '+225', iso2: 'CI' },
  { name: 'Croatia', dialCode: '+385', iso2: 'HR' },
  { name: 'Cuba', dialCode: '+53', iso2: 'CU' },
  { name: 'Cyprus', dialCode: '+357', iso2: 'CY' },
  { name: 'Czechia', dialCode: '+420', iso2: 'CZ' },
  { name: 'Denmark', dialCode: '+45', iso2: 'DK', phoneLength: [8, 8] },
  { name: 'Djibouti', dialCode: '+253', iso2: 'DJ', phoneLength: [8, 8] },
  { name: 'Dominica', dialCode: '+1767', iso2: 'DM' },
  { name: 'Dominican Republic', dialCode: '+1809', iso2: 'DO' },
  { name: 'Ecuador', dialCode: '+593', iso2: 'EC', phoneLength: [9, 9] },
  { name: 'Egypt', dialCode: '+20', iso2: 'EG', phoneLength: [10, 10] },
  { name: 'El Salvador', dialCode: '+503', iso2: 'SV' },
  { name: 'Equatorial Guinea', dialCode: '+240', iso2: 'GQ' },
  { name: 'Eritrea', dialCode: '+291', iso2: 'ER', phoneLength: [7, 7] },
  { name: 'Estonia', dialCode: '+372', iso2: 'EE' },
  { name: 'Eswatini', dialCode: '+268', iso2: 'SZ' },
  { name: 'Ethiopia', dialCode: '+251', iso2: 'ET', phoneLength: [9, 9] },
  { name: 'Fiji', dialCode: '+679', iso2: 'FJ' },
  { name: 'Finland', dialCode: '+358', iso2: 'FI', phoneLength: [6, 9] },
  { name: 'France', dialCode: '+33', iso2: 'FR', phoneLength: [9, 9] },
  { name: 'Gabon', dialCode: '+241', iso2: 'GA' },
  { name: 'Gambia', dialCode: '+220', iso2: 'GM' },
  { name: 'Georgia', dialCode: '+995', iso2: 'GE', phoneLength: [9, 9] },
  { name: 'Germany', dialCode: '+49', iso2: 'DE', phoneLength: [10, 11] },
  { name: 'Ghana', dialCode: '+233', iso2: 'GH', phoneLength: [9, 9] },
  { name: 'Greece', dialCode: '+30', iso2: 'GR' },
  { name: 'Grenada', dialCode: '+1473', iso2: 'GD' },
  { name: 'Guatemala', dialCode: '+502', iso2: 'GT' },
  { name: 'Guinea', dialCode: '+224', iso2: 'GN' },
  { name: 'Guinea-Bissau', dialCode: '+245', iso2: 'GW' },
  { name: 'Guyana', dialCode: '+592', iso2: 'GY' },
  { name: 'Haiti', dialCode: '+509', iso2: 'HT' },
  { name: 'Honduras', dialCode: '+504', iso2: 'HN' },
  { name: 'Hong Kong', dialCode: '+852', iso2: 'HK' },
  { name: 'Hungary', dialCode: '+36', iso2: 'HU' },
  { name: 'Iceland', dialCode: '+354', iso2: 'IS', phoneLength: [7, 7] },
  { name: 'India', dialCode: '+91', iso2: 'IN', phoneLength: [10, 10] },
  { name: 'Indonesia', dialCode: '+62', iso2: 'ID', phoneLength: [9, 12] },
  { name: 'Iran', dialCode: '+98', iso2: 'IR', phoneLength: [10, 10] },
  { name: 'Iraq', dialCode: '+964', iso2: 'IQ', phoneLength: [10, 10] },
  { name: 'Ireland', dialCode: '+353', iso2: 'IE', phoneLength: [7, 9] },
  { name: 'Israel', dialCode: '+972', iso2: 'IL', phoneLength: [8, 9] },
  { name: 'Italy', dialCode: '+39', iso2: 'IT', phoneLength: [9, 10] },
  { name: 'Jamaica', dialCode: '+1876', iso2: 'JM' },
  { name: 'Japan', dialCode: '+81', iso2: 'JP', phoneLength: [10, 10] },
  { name: 'Jordan', dialCode: '+962', iso2: 'JO', phoneLength: [9, 9] },
  { name: 'Kazakhstan', dialCode: '+7', iso2: 'KZ', phoneLength: [10, 10] },
  { name: 'Kenya', dialCode: '+254', iso2: 'KE', phoneLength: [9, 9] },
  { name: 'Kiribati', dialCode: '+686', iso2: 'KI' },
  { name: 'Kuwait', dialCode: '+965', iso2: 'KW', phoneLength: [7, 8] },
  { name: 'Kyrgyzstan', dialCode: '+996', iso2: 'KG' },
  { name: 'Laos', dialCode: '+856', iso2: 'LA', phoneLength: [8, 9] },
  { name: 'Latvia', dialCode: '+371', iso2: 'LV' },
  { name: 'Lebanon', dialCode: '+961', iso2: 'LB', phoneLength: [7, 8] },
  { name: 'Lesotho', dialCode: '+266', iso2: 'LS' },
  { name: 'Liberia', dialCode: '+231', iso2: 'LR' },
  { name: 'Libya', dialCode: '+218', iso2: 'LY', phoneLength: [9, 9] },
  { name: 'Liechtenstein', dialCode: '+423', iso2: 'LI' },
  { name: 'Lithuania', dialCode: '+370', iso2: 'LT' },
  { name: 'Luxembourg', dialCode: '+352', iso2: 'LU' },
  { name: 'Madagascar', dialCode: '+261', iso2: 'MG' },
  { name: 'Malawi', dialCode: '+265', iso2: 'MW' },
  { name: 'Malaysia', dialCode: '+60', iso2: 'MY', phoneLength: [8, 10] },
  { name: 'Maldives', dialCode: '+960', iso2: 'MV' },
  { name: 'Mali', dialCode: '+223', iso2: 'ML' },
  { name: 'Malta', dialCode: '+356', iso2: 'MT' },
  { name: 'Mauritania', dialCode: '+222', iso2: 'MR' },
  { name: 'Mauritius', dialCode: '+230', iso2: 'MU' },
  { name: 'Mexico', dialCode: '+52', iso2: 'MX', phoneLength: [10, 10] },
  { name: 'Moldova', dialCode: '+373', iso2: 'MD', phoneLength: [8, 8] },
  { name: 'Monaco', dialCode: '+377', iso2: 'MC' },
  { name: 'Mongolia', dialCode: '+976', iso2: 'MN' },
  { name: 'Montenegro', dialCode: '+382', iso2: 'ME' },
  { name: 'Morocco', dialCode: '+212', iso2: 'MA', phoneLength: [9, 9] },
  { name: 'Mozambique', dialCode: '+258', iso2: 'MZ' },
  { name: 'Myanmar', dialCode: '+95', iso2: 'MM', phoneLength: [7, 10] },
  { name: 'Namibia', dialCode: '+264', iso2: 'NA' },
  { name: 'Nepal', dialCode: '+977', iso2: 'NP', phoneLength: [9, 10] },
  { name: 'Netherlands', dialCode: '+31', iso2: 'NL', phoneLength: [9, 9] },
  { name: 'New Zealand', dialCode: '+64', iso2: 'NZ', phoneLength: [8, 9] },
  { name: 'Nicaragua', dialCode: '+505', iso2: 'NI' },
  { name: 'Niger', dialCode: '+227', iso2: 'NE' },
  { name: 'Nigeria', dialCode: '+234', iso2: 'NG', phoneLength: [10, 10] },
  { name: 'North Korea', dialCode: '+850', iso2: 'KP' },
  { name: 'North Macedonia', dialCode: '+389', iso2: 'MK' },
  { name: 'Norway', dialCode: '+47', iso2: 'NO', phoneLength: [8, 8] },
  { name: 'Oman', dialCode: '+968', iso2: 'OM', phoneLength: [7, 8] },
  { name: 'Pakistan', dialCode: '+92', iso2: 'PK', phoneLength: [9, 10] },
  { name: 'Panama', dialCode: '+507', iso2: 'PA' },
  { name: 'Papua New Guinea', dialCode: '+675', iso2: 'PG' },
  { name: 'Paraguay', dialCode: '+595', iso2: 'PY', phoneLength: [9, 9] },
  { name: 'Peru', dialCode: '+51', iso2: 'PE', phoneLength: [9, 9] },
  { name: 'Philippines', dialCode: '+63', iso2: 'PH', phoneLength: [10, 10] },
  { name: 'Poland', dialCode: '+48', iso2: 'PL', phoneLength: [9, 9] },
  { name: 'Portugal', dialCode: '+351', iso2: 'PT', phoneLength: [9, 9] },
  { name: 'Qatar', dialCode: '+974', iso2: 'QA', phoneLength: [7, 8] },
  { name: 'Romania', dialCode: '+40', iso2: 'RO' },
  { name: 'Russia', dialCode: '+7', iso2: 'RU', phoneLength: [10, 10] },
  { name: 'Rwanda', dialCode: '+250', iso2: 'RW', phoneLength: [9, 9] },
  { name: 'Saudi Arabia', dialCode: '+966', iso2: 'SA', phoneLength: [9, 9] },
  { name: 'Senegal', dialCode: '+221', iso2: 'SN' },
  { name: 'Serbia', dialCode: '+381', iso2: 'RS' },
  { name: 'Seychelles', dialCode: '+248', iso2: 'SC' },
  { name: 'Sierra Leone', dialCode: '+232', iso2: 'SL' },
  { name: 'Singapore', dialCode: '+65', iso2: 'SG', phoneLength: [8, 8] },
  { name: 'Slovakia', dialCode: '+421', iso2: 'SK' },
  { name: 'Slovenia', dialCode: '+386', iso2: 'SI' },
  { name: 'Somalia', dialCode: '+252', iso2: 'SO', phoneLength: [7, 8] },
  { name: 'South Africa', dialCode: '+27', iso2: 'ZA', phoneLength: [9, 9] },
  { name: 'South Korea', dialCode: '+82', iso2: 'KR', phoneLength: [9, 10] },
  { name: 'South Sudan', dialCode: '+211', iso2: 'SS', phoneLength: [9, 9] },
  { name: 'Spain', dialCode: '+34', iso2: 'ES', phoneLength: [9, 9] },
  { name: 'Sri Lanka', dialCode: '+94', iso2: 'LK', phoneLength: [9, 9] },
  { name: 'Sudan', dialCode: '+249', iso2: 'SD', phoneLength: [9, 9] },
  { name: 'Suriname', dialCode: '+597', iso2: 'SR' },
  { name: 'Sweden', dialCode: '+46', iso2: 'SE', phoneLength: [7, 9] },
  { name: 'Switzerland', dialCode: '+41', iso2: 'CH', phoneLength: [9, 9] },
  { name: 'Syria', dialCode: '+963', iso2: 'SY' },
  { name: 'Taiwan', dialCode: '+886', iso2: 'TW' },
  { name: 'Tajikistan', dialCode: '+992', iso2: 'TJ' },
  { name: 'Tanzania', dialCode: '+255', iso2: 'TZ', phoneLength: [9, 9] },
  { name: 'Thailand', dialCode: '+66', iso2: 'TH', phoneLength: [9, 9] },
  { name: 'Togo', dialCode: '+228', iso2: 'TG' },
  { name: 'Trinidad and Tobago', dialCode: '+1868', iso2: 'TT' },
  { name: 'Tunisia', dialCode: '+216', iso2: 'TN', phoneLength: [8, 8] },
  { name: 'Turkey', dialCode: '+90', iso2: 'TR', phoneLength: [10, 10] },
  { name: 'Turkmenistan', dialCode: '+993', iso2: 'TM' },
  { name: 'Uganda', dialCode: '+256', iso2: 'UG', phoneLength: [9, 9] },
  { name: 'Ukraine', dialCode: '+380', iso2: 'UA', phoneLength: [9, 9] },
  { name: 'United Arab Emirates', dialCode: '+971', iso2: 'AE', phoneLength: [9, 9] },
  { name: 'United Kingdom', dialCode: '+44', iso2: 'GB', phoneLength: [10, 10] },
  { name: 'United States', dialCode: '+1', iso2: 'US', phoneLength: [10, 10] },
  { name: 'Uruguay', dialCode: '+598', iso2: 'UY', phoneLength: [8, 8] },
  { name: 'Uzbekistan', dialCode: '+998', iso2: 'UZ' },
  { name: 'Vanuatu', dialCode: '+678', iso2: 'VU' },
  { name: 'Venezuela', dialCode: '+58', iso2: 'VE', phoneLength: [10, 10] },
  { name: 'Vietnam', dialCode: '+84', iso2: 'VN', phoneLength: [9, 10] },
  { name: 'Yemen', dialCode: '+967', iso2: 'YE' },
  { name: 'Zambia', dialCode: '+260', iso2: 'ZM' },
  { name: 'Zimbabwe', dialCode: '+263', iso2: 'ZW' },
];
