// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Deliberately NOT the same DATABASE_URL the running app uses (see
  // src/lib/prisma.ts) — that one now points at Supabase's Transaction
  // pooler so the app's frequent short-lived queries (AutoRefresh polling on
  // many pages) don't blow past the Session pooler's much lower connection
  // ceiling. `prisma migrate deploy` needs a session-scoped connection for
  // its advisory lock (it hangs indefinitely under transaction pooling), so
  // it gets its own URL here, used only briefly during each build.
  datasource: {
    url: process.env["MIGRATE_DATABASE_URL"],
  },
});
